---
# Demo ACI Playbook
- name: Configuring Example Tenant
  hosts: "{{ host_name }}"
  connection: local
  gather_facts: no

  tasks:
  - name: Create a New Tenant
    aci_tenant:
        hostname: "{{ hostname }}"
        #hostname: sandboxapicdc.cisco.com
        username: "{{ username }}"
        password: "{{ password }}"
        #username: admin
        #password: ciscopsdt
        #private_key: "{{ new_user }}.key"
        #tenant: "CiscoLive"
        tenant: "{{ tenant }}"
        description: "Tenant configured by Ansible"
        validate_certs: no
        state: present
        
        

