---
# Demo ACI Playbook
- name: Configuring Example Tenant
  hosts: devnet
  connection: local
  gather_facts: no

  tasks:
  - name: Create a New Tenant
    aci_tenant:
        #hostname: "{{ inventory_hostname }}"
        #username: "{{ username }}"
        #password: "{{ password }}"
        username: admin
        password: ciscopsdt
        #private_key: "{{ new_user }}.key"
        tenant: "CiscoLive"
        description: "Tenant configured by Ansible"
        validate_certs: no
        state: present

