all:
  children:
    apic:
      hosts:
        198.19.202.94:
          new_user: ansible
          new_user_pass: C1sco12345
          password: C1sco12345!
          username: admin
    ungrouped: {}
