---
- name: Tenant configuration with rest call
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Add a tenant using a JSON string
    aci_rest:
      hostname: "{{ inventory_hostname }}"
      username: "{{ new_user }}"
      #password: "{{ password }}"
      private_key: "{{ new_user }}.key"
      validate_certs: no
      path: /api/mo/uni.json
      method: post
      content: 
        {
          "fvTenant": {
            "attributes": {
              "name": "ansible_rest_tenant",
              "dn": "uni/tn-ansible_rest_tenant",
              "descr": "Tenana configured with Ansible and ACI REST API"
            }
          }
        }
    delegate_to: localhost