---
# Demo ACI Playbook
- name: Configuring Example Tenant
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Create a New Tenant
    aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ new_user }}"
        #password: "{{ password }}"
        private_key: "{{ new_user }}.key"
        tenant: "ACC_Basic_Tenant"
        description: "Tenant configured by Ansible with Signature-based auth"
        validate_certs: no
        state: present

